Repository GSG-G10/ReactNative-Projects-App, pull requests merged in 2021-12, with the labels that each got.

#8 Create the first file structure
  .eslintrc.json
  .expo-shared/assets.json
  .gitignore
  .vscode/settings.json
  App.tsx
  app.json
  babel.config.js
  package-lock.json
  package.json
  src/assets/fonts/SpaceMono-Regular.ttf
  src/assets/images/adaptive-icon.png
  src/assets/images/favicon.png
  src/assets/images/icon.png
  src/assets/images/splash.png
  src/components/EditScreenInfo.tsx
  src/components/StyledText.tsx
  src/components/Themed.tsx
  src/components/__tests__/StyledText-test.js
  src/constants/Colors.ts
  src/constants/Layout.ts
  src/hooks/useCachedResources.ts
  src/hooks/useColorScheme.ts
  src/navigation/LinkingConfiguration.ts
  src/navigation/index.tsx
  src/screens/MessagesScreen.tsx
  src/screens/NotFoundScreen.tsx
  src/screens/ProjectsScreen.tsx
  src/screens/SplashScreen.tsx
  src/screens/index.tsx
  src/types.tsx
  tsconfig.json
Labels: Done

#9 fix json import error
  app.json
Labels: Done

#10 Create Firebase integration with app
  .gitignore
  App.tsx
  babel.config.js
  firebase.config.js
  package-lock.json
  package.json
  src/api/getData.tsx
  src/components/EditScreenInfo.tsx
  src/components/StyledText.tsx
  src/components/Themed.tsx
  src/constants/Layout.ts
Labels: Done

#13 Create Image common component
  src/designs/Image.tsx
  src/designs/index.ts
Labels: Done

#16 Common components
  package-lock.json
  package.json
  src/components/EditScreenInfo.tsx
  src/design/Button/index.tsx
  src/design/Card/index.tsx
  src/design/Icon/index.tsx
  src/design/Text/index.tsx
  src/design/index.ts
  src/screens/ProjectsScreen.tsx
Labels: Awaiting Review

#18 Build the project screen
  src/components/OptionNavigator/index.tsx
  src/designs/Divider.tsx
  src/designs/ListGenrator.tsx
  src/designs/index.ts
  src/navigation/index.tsx
  src/screens/Estimate.tsx
  src/screens/ProjectScreen.tsx
  src/screens/ProjectsScreen.tsx
  src/screens/index.tsx
  src/screens/styles/ProjectScreenStyle.tsx
  src/types.tsx
  src/utils/handleStatusColor.ts
  src/utils/index.ts
Labels: Done

#19 Store the data from Firebase in state using Redux/Toolkit
  App.tsx
  package-lock.json
  package.json
  src/navigation/index.tsx
  src/redux/actions.ts
  src/redux/projectsListSlice.ts
  src/redux/store.ts
  src/screens/SplashScreen.tsx
Labels: Awaiting Review

#25 Handle projects from redux state
  firebase.config.js
  src/design/Card/index.tsx
  src/screens/NotFoundScreen.tsx
  src/screens/ProjectScreen.tsx
  src/screens/ProjectsScreen.tsx
  src/utils/handleStatusColor.ts
Labels: Done

#26 Add new project
  app.json
  firebase.config.js
  package-lock.json
  package.json
  src/api/firebaseStorage.ts
  src/api/getData.ts
  src/api/index.ts
  src/api/postNewProject.ts
  src/components/PickImage/index.tsx
  src/components/PickImage/styles.ts
  src/components/UseCamera/index.tsx
  src/navigation/index.tsx
  src/redux/actions.ts
  src/redux/reducers/imageSlice.ts
  src/redux/reducers/index.ts
  src/redux/reducers/projectsListSlice.ts
  src/redux/store.ts
  src/screens/NewProjectScreen.tsx
  src/screens/ProjectsScreen.tsx
  src/screens/SplashScreen.tsx
  src/screens/index.ts
  src/screens/styles/NewProjectStyle.tsx
  src/types.tsx
Labels: Done

#27 Specification screen
  package-lock.json
  src/components/ConfirmModal/index.tsx
  src/components/ConfirmModal/styles.tsx
  src/components/EditModal/index.tsx
  src/components/EditModal/styles.tsx
  src/components/SpecificationItem/index.tsx
  src/design/Text/index.tsx
  src/navigation/index.tsx
  src/screens/SpecificationsScreen.tsx
  src/screens/index.ts
  src/screens/index.tsx
Labels: Awaiting Review

#29 Resolve bugs
  firebase.config.ts
  src/api/postNewProject.ts
  src/components/PickImage/index.tsx
  src/components/UseCamera/index.tsx
  src/design/Divider/index.tsx
  src/design/Image/index.tsx
  src/design/index.ts
  src/designs/ListGenrator.tsx
  src/designs/index.ts
  src/screens/NewProjectScreen.tsx
  src/screens/ProjectScreen.tsx
  src/screens/ProjectsScreen.tsx
  src/screens/SplashScreen.tsx
  src/utils/handleStatusColor.ts
Labels: Done

#30 Resolve old package-lock file
  package-lock.json
Labels: Done, bug

#31 Build a chat real time
  App.tsx
  firebase.config.ts
  package-lock.json
  package.json
  src/api/getData.ts
  src/api/index.ts
  src/api/renderMessages.ts
  src/api/sendMessage.ts
  src/api/signIn.ts
  src/api/signUp.ts
  src/components/Chat/index.tsx
  src/screens/MessagesScreen.tsx
  src/screens/ProjectScreen.tsx
  src/screens/SignInScreen.tsx
  src/screens/SplashScreen.tsx
  src/types.tsx
Labels: Awaiting Review

#33 Sort data in projects screen
  package-lock.json
  package.json
  src/components/FilterButtonAndroid/index.tsx
  src/navigation/index.tsx
  src/redux/actions.ts
  src/redux/reducers/projectsListSlice.ts
  src/screens/ProjectsScreen.tsx
  src/types.tsx
Labels: Done
